
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package bq.cxf.tutorial.wssecuritypolicy.common;

import java.util.logging.Logger;

import bq.cxf.tutorial.wssecuritypolicy.gen.Echoservice;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-03-05T09:48:18.625-05:00
 * Generated source version: 2.7.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "echoservice",
                      portName = "echoserviceSOAP",
                      targetNamespace = "http://bq.cxf.tutorial/echoservice/",
                      wsdlLocation = "src/main/resource/bq/cxf/tutorial/wssecuritypolicy/common/echoservice.wsdl",
                      endpointInterface = "bq.cxf.tutorial.wssecuritypolicy.gen.Echoservice")
                      
public class EchoserviceImpl implements Echoservice {

    private static final Logger LOG = Logger.getLogger(EchoserviceImpl.class.getName());

    /* (non-Javadoc)
     * @see bq.cxf.tutorial.wssecuritypolicy.gen.Echoservice#echo(java.lang.String  message )*
     */
    public java.lang.String echo(java.lang.String message) { 
        LOG.info("Executing operation echo");
        System.out.println(message);
        try {
            java.lang.String _return = message;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
