
package org.example.wsdlfirst_eho;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-21T21:24:44.886-05:00
 * Generated source version: 2.7.8
 * 
 */
 
public class WsdlfirstEhco_WsdlfirstEhco_Server{

    protected WsdlfirstEhco_WsdlfirstEhco_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WsdlfirstEhcoImpl();
        String address = "http://jonathanbo.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new WsdlfirstEhco_WsdlfirstEhco_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
