package org.example.wsdlfirst_eho;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-21T21:24:44.842-05:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.example.org/wsdlfirst_eho/", name = "wsdlfirst_ehco")
@XmlSeeAlso({ObjectFactory.class})
public interface WsdlfirstEhco {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "echoString", targetNamespace = "http://www.example.org/wsdlfirst_eho/", className = "org.example.wsdlfirst_eho.EchoString")
    @WebMethod(action = "http://www.example.org/wsdlfirst_eho/echoString")
    @ResponseWrapper(localName = "echoStringResponse", targetNamespace = "http://www.example.org/wsdlfirst_eho/", className = "org.example.wsdlfirst_eho.EchoStringResponse")
    public java.lang.String echoString(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebMethod
    public void echoObject(
        @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "parameters", targetNamespace = "")
        javax.xml.ws.Holder<Message> parameters
    );
}
