
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.wsdlfirst_eho;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-21T21:24:44.556-05:00
 * Generated source version: 2.7.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "wsdlfirst_ehco",
                      portName = "wsdlfirst_ehco",
                      targetNamespace = "http://www.example.org/wsdlfirst_eho/",
                      wsdlLocation = "/home/boqi/git/jaxws/src/main/java/bq/cxf/tutorial/simple2/server/wsdlfirst_echo.wsdl",
                      endpointInterface = "org.example.wsdlfirst_eho.WsdlfirstEhco")
                      
public class WsdlfirstEhcoImpl implements WsdlfirstEhco {

    private static final Logger LOG = Logger.getLogger(WsdlfirstEhcoImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.wsdlfirst_eho.WsdlfirstEhco#echoString(java.lang.String  msg )*
     */
    public java.lang.String echoString(java.lang.String msg) { 
        LOG.info("Executing operation echoString");
        System.out.println(msg);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.wsdlfirst_eho.WsdlfirstEhco#echoObject(org.example.wsdlfirst_eho.Message  parameters )*
     */
    public void echoObject(javax.xml.ws.Holder<Message> parameters) { 
        LOG.info("Executing operation echoObject");
        System.out.println(parameters.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
